package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/opencontainers/runc/libcontainer/apparmor"
	"github.com/opencontainers/runtime-spec/specs-go"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

const traceSyscallAnnotation = "io.containers.trace-syscall"

var defaultSeccompHookPaths = []string{
	"/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
	"/usr/local/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
}

var defaultCapablePaths = []string{
	"/usr/share/bcc/tools/capable",
	"/usr/sbin/capable-bpfcc",
}

const appArmorScanReadme = `AppArmor (automatic with --security-scan)
========================================

When AppArmor is enabled on the host, runc loads generated/apparmor.profile
(complain mode via profile flags) before the container runs, sets
process.apparmorProfile, and unloads the profile on poststop.

If AppArmor is disabled, the profile file is still written for reference.
See generated/apparmor-load.log after each run.
`

func buildAppArmorProfileSource(profileName string) string {
	return fmt.Sprintf(`#include <tunables/global>

profile %s flags=(complain, attach_disconnected, mediate_deleted) {
  #include <abstractions/base>
  # Auto-generated by runc --security-scan (complain mode in profile flags).
}
`, profileName)
}

func securityScanAppArmorProfileName(containerID string) string {
	const prefix = "runc_scan_"
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range containerID {
		switch {
		case unicode.IsLetter(r), unicode.IsDigit(r):
			b.WriteRune(r)
		case r == '-', r == '_':
			b.WriteByte('_')
		}
	}
	name := b.String()
	if len(name) <= len(prefix) {
		name = prefix + "x"
	}
	if len(name) > 200 {
		name = name[:200]
	}
	return name
}

func applySecurityScan(spec *specs.Spec, ctx *cli.Context, containerID string) error {
	if !ctx.Bool("security-scan") {
		return nil
	}
	bundleDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("security-scan: getwd: %w", err)
	}
	bundleDir, err = filepath.Abs(bundleDir)
	if err != nil {
		return fmt.Errorf("security-scan: abs bundle: %w", err)
	}
	genDir := filepath.Join(bundleDir, "generated")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return fmt.Errorf("security-scan: mkdir generated: %w", err)
	}

	hookPath := strings.TrimSpace(ctx.String("scan-seccomp-hook"))
	if hookPath == "" {
		for _, p := range defaultSeccompHookPaths {
			if st, err := os.Stat(p); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
				hookPath = p
				logrus.Infof("security-scan: using seccomp hook %q", hookPath)
				break
			}
		}
	}
	if hookPath == "" {
		return fmt.Errorf("security-scan: no oci-seccomp-bpf-hook found; install it or pass --scan-seccomp-hook PATH (e.g. contrib stub for tests)")
	}
	hookPath, err = filepath.Abs(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: abs hook path: %w", err)
	}
	st, err := os.Stat(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: stat seccomp hook: %w", err)
	}
	if st.IsDir() || st.Mode()&0o111 == 0 {
		return fmt.Errorf("security-scan: seccomp hook must be an executable file: %s", hookPath)
	}

	seccompOut := filepath.Join(genDir, "seccomp.json")
	annotation := "of:" + seccompOut
	if spec.Annotations == nil {
		spec.Annotations = map[string]string{}
	}
	if prev, ok := spec.Annotations[traceSyscallAnnotation]; ok && prev != annotation {
		logrus.Warnf("security-scan: overwriting annotation %q (was %q)", traceSyscallAnnotation, prev)
	}
	spec.Annotations[traceSyscallAnnotation] = annotation

	if spec.Hooks == nil {
		spec.Hooks = &specs.Hooks{}
	}
	secHook := specs.Hook{
		Path: hookPath,
		Args: []string{filepath.Base(hookPath), "-s"},
	}
	spec.Hooks.Prestart = append(spec.Hooks.Prestart, secHook)

	capScriptPath := filepath.Join(genDir, ".runc_cap_hook.sh")
	capBody := buildCapHookScript(bundleDir)
	if err := os.WriteFile(capScriptPath, []byte(capBody), 0o755); err != nil {
		return fmt.Errorf("security-scan: write poststart cap hook: %w", err)
	}
	postHook := specs.Hook{
		Path: capScriptPath,
		Args: []string{filepath.Base(capScriptPath)},
	}
	if capBin := resolveCapableBinary(ctx); capBin != "" {
		postHook.Env = []string{
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"RUNC_SCAN_CAPABLE=" + capBin,
		}
		logrus.Infof("security-scan: tracing used caps in background via %q (see generated/capable-bpfcc.log)", capBin)
	}
	spec.Hooks.Poststart = append(spec.Hooks.Poststart, postHook)

	aaProfName := securityScanAppArmorProfileName(containerID)
	aaProfPath := filepath.Join(genDir, "apparmor.profile")
	if err := os.WriteFile(aaProfPath, []byte(buildAppArmorProfileSource(aaProfName)), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor.profile: %w", err)
	}
	aaReadme := filepath.Join(genDir, "apparmor-README.txt")
	if err := os.WriteFile(aaReadme, []byte(appArmorScanReadme), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor readme: %w", err)
	}

	if apparmor.IsEnabled() {
		loadPath := filepath.Join(genDir, ".runc_aa_load.sh")
		if err := os.WriteFile(loadPath, []byte(buildAALoadScript()), 0o755); err != nil {
			return fmt.Errorf("security-scan: write aa load hook: %w", err)
		}
		unloadPath := filepath.Join(genDir, ".runc_aa_unload.sh")
		if err := os.WriteFile(unloadPath, []byte(buildAAUnloadScript()), 0o755); err != nil {
			return fmt.Errorf("security-scan: write aa unload hook: %w", err)
		}
		aaLog := filepath.Join(genDir, "apparmor-load.log")
		env := []string{
			"PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin",
			"RUNC_AA_PROFILE_PATH=" + aaProfPath,
			"RUNC_AA_LOG=" + aaLog,
		}
		loadHook := specs.Hook{
			Path: loadPath,
			Args: []string{filepath.Base(loadPath)},
			Env:  env,
		}
		spec.Hooks.CreateRuntime = append([]specs.Hook{loadHook}, spec.Hooks.CreateRuntime...)
		unloadHook := specs.Hook{
			Path: unloadPath,
			Args: []string{filepath.Base(unloadPath)},
			Env:  env,
		}
		spec.Hooks.Poststop = append(spec.Hooks.Poststop, unloadHook)
		if spec.Process == nil {
			spec.Process = &specs.Process{}
		}
		if spec.Process.ApparmorProfile != "" && spec.Process.ApparmorProfile != aaProfName {
			logrus.Warnf("security-scan: replacing apparmorProfile %q with scan profile %q", spec.Process.ApparmorProfile, aaProfName)
		}
		spec.Process.ApparmorProfile = aaProfName
		logrus.Infof("security-scan: AppArmor profile %q (complain) will load from %q", aaProfName, aaProfPath)
	} else {
		logrus.Info("security-scan: AppArmor disabled on host; wrote apparmor.profile but did not set process.apparmorProfile or hooks")
	}

	logrus.Infof("security-scan: bundle %q; artifacts under %s", bundleDir, genDir)
	return nil
}

func buildAALoadScript() string {
	return `#!/bin/sh
: "${RUNC_AA_PROFILE_PATH:?}"
: "${RUNC_AA_LOG:?}"
exec >>"$RUNC_AA_LOG" 2>&1
echo "---- load $(date) ----"
if ! command -v apparmor_parser >/dev/null 2>&1; then
  echo "apparmor_parser not found; skipping"
  exit 0
fi
if apparmor_parser -r "$RUNC_AA_PROFILE_PATH"; then
  echo "apparmor_parser -r ok"
else
  echo "apparmor_parser -r failed (non-fatal for hook)"
fi
exit 0
`
}

func buildAAUnloadScript() string {
	return `#!/bin/sh
: "${RUNC_AA_PROFILE_PATH:?}"
: "${RUNC_AA_LOG:?}"
exec >>"$RUNC_AA_LOG" 2>&1
echo "---- unload $(date) ----"
if command -v apparmor_parser >/dev/null 2>&1; then
  apparmor_parser -R "$RUNC_AA_PROFILE_PATH" || echo "apparmor_parser -R failed (non-fatal)"
fi
exit 0
`
}

func resolveCapableBinary(ctx *cli.Context) string {
	p := strings.TrimSpace(ctx.String("scan-capable"))
	if p != "" {
		abs, err := filepath.Abs(p)
		if err != nil {
			logrus.Warnf("security-scan: scan-capable path: %v", err)
			return ""
		}
		st, err := os.Stat(abs)
		if err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
			logrus.Warnf("security-scan: --scan-capable %q is not an executable file", abs)
			return ""
		}
		return abs
	}
	if path, err := exec.LookPath("capable-bpfcc"); err == nil {
		return path
	}
	for _, try := range defaultCapablePaths {
		if st, err := os.Stat(try); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
			return try
		}
	}
	return ""
}

func shellSingleQuote(s string) string {
	return `'` + strings.ReplaceAll(s, `'`, `'\''`) + `'`
}

func buildCapHookScript(bundleDir string) string {
	q := shellSingleQuote(bundleDir)
	return fmt.Sprintf(`#!/bin/sh
set -e
state=$(cat)
bundle=%s
gen="$bundle/generated"
mkdir -p "$gen"
pid=$(printf '%%s' "$state" | sed -n 's/.*"pid": *\([0-9][0-9]*\).*/\1/p' | head -n1)
if [ -z "$pid" ]; then
  printf 'security-scan: could not parse pid from hook state\n' >>"$gen/capabilities-from-proc-status.txt"
  exit 0
fi
if [ -r "/proc/$pid/status" ]; then
  grep '^Cap' "/proc/$pid/status" >"$gen/capabilities-from-proc-status.txt" || true
else
  printf 'security-scan: /proc/%%s/status not readable\n' "$pid" >"$gen/capabilities-from-proc-status.txt"
fi
if [ -n "${RUNC_SCAN_CAPABLE:-}" ] && [ -x "$RUNC_SCAN_CAPABLE" ]; then
  : >>"$gen/capable-bpfcc.log"
  nohup "$RUNC_SCAN_CAPABLE" -p "$pid" >>"$gen/capable-bpfcc.log" 2>&1 &
fi
`, q)
}
