package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/moby/sys/capability"
	"github.com/opencontainers/runc/libcontainer/apparmor"
	"github.com/opencontainers/runtime-spec/specs-go"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

const traceSyscallAnnotation = "io.containers.trace-syscall"

var defaultSeccompHookPaths = []string{
	"/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
	"/usr/local/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
}

var defaultCapablePaths = []string{
	"/usr/share/bcc/tools/capable",
	"/usr/sbin/capable-bpfcc",
}

const appArmorScanReadme = `AppArmor (automatic with --security-scan)
========================================

When AppArmor is enabled on the host, runc loads generated/apparmor.profile
(complain mode via profile flags) before the container runs, sets
process.apparmorProfile, and unloads the profile on poststop.

If AppArmor is disabled, the profile file is still written for reference.
See generated/apparmor-load.log after each run.
`

func buildAppArmorProfileSource(profileName string) string {
	return fmt.Sprintf(`#include <tunables/global>

profile %s flags=(complain, attach_disconnected, mediate_deleted) {
  #include <abstractions/base>
  # Auto-generated by runc --security-scan (complain mode in profile flags).
}
`, profileName)
}

func securityScanAppArmorProfileName(containerID string) string {
	const prefix = "runc_scan_"
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range containerID {
		switch {
		case unicode.IsLetter(r), unicode.IsDigit(r):
			b.WriteRune(r)
		case r == '-', r == '_':
			b.WriteByte('_')
		}
	}
	name := b.String()
	if len(name) <= len(prefix) {
		name = prefix + "x"
	}
	if len(name) > 200 {
		name = name[:200]
	}
	return name
}

func applySecurityScan(spec *specs.Spec, ctx *cli.Context, containerID string) error {
	if !ctx.Bool("security-scan") {
		return nil
	}
	bundleDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("security-scan: getwd: %w", err)
	}
	bundleDir, err = filepath.Abs(bundleDir)
	if err != nil {
		return fmt.Errorf("security-scan: abs bundle: %w", err)
	}
	genDir := filepath.Join(bundleDir, "generated")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return fmt.Errorf("security-scan: mkdir generated: %w", err)
	}

	runcBin, err := resolveRuncSelfExec()
	if err != nil {
		return err
	}

	relaxSpecForScan(spec)
	grantAllCapsForScan(spec)
	warnIfRootInScan(spec)

	hookPath := strings.TrimSpace(ctx.String("scan-seccomp-hook"))
	if hookPath == "" {
		for _, p := range defaultSeccompHookPaths {
			if st, err := os.Stat(p); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
				hookPath = p
				logrus.Infof("security-scan: using seccomp hook %q", hookPath)
				break
			}
		}
	}
	if hookPath == "" {
		return fmt.Errorf("security-scan: no oci-seccomp-bpf-hook found; install it or pass --scan-seccomp-hook PATH (e.g. contrib stub for tests)")
	}
	hookPath, err = filepath.Abs(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: abs hook path: %w", err)
	}
	st, err := os.Stat(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: stat seccomp hook: %w", err)
	}
	if st.IsDir() || st.Mode()&0o111 == 0 {
		return fmt.Errorf("security-scan: seccomp hook must be an executable file: %s", hookPath)
	}

	seccompOut := filepath.Join(genDir, "seccomp.json")
	annotation := "of:" + seccompOut
	if spec.Annotations == nil {
		spec.Annotations = map[string]string{}
	}
	if prev, ok := spec.Annotations[traceSyscallAnnotation]; ok && prev != annotation {
		logrus.Warnf("security-scan: overwriting annotation %q (was %q)", traceSyscallAnnotation, prev)
	}
	spec.Annotations[traceSyscallAnnotation] = annotation

	if spec.Hooks == nil {
		spec.Hooks = &specs.Hooks{}
	}
	secHook := specs.Hook{
		Path: hookPath,
		Args: []string{filepath.Base(hookPath), "-s"},
	}
	spec.Hooks.Prestart = append(spec.Hooks.Prestart, secHook)

	snapshotHook := specs.Hook{
		Path: runcBin,
		Args: []string{"runc", "scan-cap-snapshot"},
	}
	spec.Hooks.Poststart = append(spec.Hooks.Poststart, snapshotHook)

	if capBin := resolveCapableBinary(ctx); capBin != "" {
		traceEnv := []string{
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			envScanCapableBin + "=" + capBin,
		}
		spec.Hooks.Poststart = append(spec.Hooks.Poststart, specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-cap-trace-start"},
			Env:  traceEnv,
		})
		// Stop hook is prepended so it runs before AA-unload and any
		// other poststop hook a user (or we) might add later. The hook
		// itself is also our barrier: by the time finalizeSecurityScan
		// runs, the tracer has exited and capable-bpfcc.log is closed.
		spec.Hooks.Poststop = append([]specs.Hook{{
			Path: runcBin,
			Args: []string{"runc", "scan-cap-trace-stop"},
		}}, spec.Hooks.Poststop...)
		logrus.Infof("security-scan: tracing used caps in background via %q (see generated/%s)", capBin, scanCapTraceLogFile)
	}

	aaProfName := securityScanAppArmorProfileName(containerID)
	aaProfPath := filepath.Join(genDir, "apparmor.profile")
	if err := os.WriteFile(aaProfPath, []byte(buildAppArmorProfileSource(aaProfName)), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor.profile: %w", err)
	}
	aaReadme := filepath.Join(genDir, "apparmor-README.txt")
	if err := os.WriteFile(aaReadme, []byte(appArmorScanReadme), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor readme: %w", err)
	}

	if apparmor.IsEnabled() {
		aaLog := filepath.Join(genDir, "apparmor-load.log")
		env := []string{
			"PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin",
			envScanAAProfilePath + "=" + aaProfPath,
			envScanAALog + "=" + aaLog,
		}
		loadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-load"},
			Env:  env,
		}
		spec.Hooks.CreateRuntime = append([]specs.Hook{loadHook}, spec.Hooks.CreateRuntime...)
		unloadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-unload"},
			Env:  env,
		}
		spec.Hooks.Poststop = append(spec.Hooks.Poststop, unloadHook)
		if spec.Process == nil {
			spec.Process = &specs.Process{}
		}
		if spec.Process.ApparmorProfile != "" && spec.Process.ApparmorProfile != aaProfName {
			logrus.Warnf("security-scan: replacing apparmorProfile %q with scan profile %q", spec.Process.ApparmorProfile, aaProfName)
		}
		spec.Process.ApparmorProfile = aaProfName
		logrus.Infof("security-scan: AppArmor profile %q (complain) will load from %q via runc self-exec", aaProfName, aaProfPath)
	} else {
		logrus.Info("security-scan: AppArmor disabled on host; wrote apparmor.profile but did not set process.apparmorProfile or hooks")
	}

	logrus.Infof("security-scan: bundle %q; artifacts under %s", bundleDir, genDir)
	return nil
}

func resolveCapableBinary(ctx *cli.Context) string {
	p := strings.TrimSpace(ctx.String("scan-capable"))
	if p != "" {
		abs, err := filepath.Abs(p)
		if err != nil {
			logrus.Warnf("security-scan: scan-capable path: %v", err)
			return ""
		}
		st, err := os.Stat(abs)
		if err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
			logrus.Warnf("security-scan: --scan-capable %q is not an executable file", abs)
			return ""
		}
		return abs
	}
	if path, err := exec.LookPath("capable-bpfcc"); err == nil {
		return path
	}
	for _, try := range defaultCapablePaths {
		if st, err := os.Stat(try); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
			return try
		}
	}
	return ""
}

// relaxSpecForScan turns off the host-supplied security policies that
// would otherwise muffle the trace. We need every syscall and every
// capability check to actually reach the kernel hooks our tracers ride
// on, so seccomp/SELinux/NoNewPrivileges are stripped from the spec for
// the duration of the scan run. The on-disk config.json is left alone;
// finalizeSecurityScan only ever rewrites Process.Capabilities, so the
// user's original seccomp/selinux/NNP survive into subsequent runs.
//
// AppArmor is handled separately further down in applySecurityScan: the
// generated complain-mode profile is what gets wired in via
// process.apparmorProfile, replacing whatever the user had set.
func relaxSpecForScan(spec *specs.Spec) {
	if spec == nil {
		return
	}
	var cleared []string
	if spec.Linux != nil && spec.Linux.Seccomp != nil {
		spec.Linux.Seccomp = nil
		cleared = append(cleared, "linux.seccomp")
	}
	if spec.Process != nil {
		if spec.Process.SelinuxLabel != "" {
			spec.Process.SelinuxLabel = ""
			cleared = append(cleared, "process.selinuxLabel")
		}
		if spec.Process.NoNewPrivileges {
			spec.Process.NoNewPrivileges = false
			cleared = append(cleared, "process.noNewPrivileges")
		}
	}
	if len(cleared) > 0 {
		logrus.Infof("security-scan: relaxed in-memory spec fields: %s", strings.Join(cleared, ", "))
	}
}

// grantAllCapsForScan replaces process.capabilities with the full set
// of capabilities the running kernel knows about. Combined with the
// non-root uid recommendation, this gives the application enough
// privilege to perform every operation it would attempt in production
// while still routing every privileged check through cap_capable so
// the BCC tracer can record it. The set is written into all five OCI
// capability buckets (bounding/effective/permitted/inheritable/ambient)
// so caps survive across exec(2).
//
// finalizeSecurityScan compares the on-disk config.json against what
// was actually observed during the run, so this in-memory grant does
// not leak into subsequent runs.
func grantAllCapsForScan(spec *specs.Spec) {
	if spec == nil {
		return
	}
	caps := allKnownCapabilityNames()
	if len(caps) == 0 {
		logrus.Warn("security-scan: kernel reported no capabilities; cap-trace coverage will be limited")
		return
	}
	if spec.Process == nil {
		spec.Process = &specs.Process{}
	}
	if spec.Process.Capabilities == nil {
		spec.Process.Capabilities = &specs.LinuxCapabilities{}
	}
	spec.Process.Capabilities.Bounding = caps
	spec.Process.Capabilities.Effective = caps
	spec.Process.Capabilities.Permitted = caps
	spec.Process.Capabilities.Inheritable = caps
	spec.Process.Capabilities.Ambient = caps
	logrus.Infof("security-scan: granted %d capabilities for scan run (will be narrowed by finalize)", len(caps))
}

// warnIfRootInScan logs a warning when the bundle asks for uid 0.
// We do not rewrite the spec - some workloads genuinely need root and
// forcing a non-root uid would break them - but cap_capable is only
// called for non-root tasks, so the cap-trace coverage degrades sharply
// when the init process runs as root. Documented in SCANNER_PROGRESS.
func warnIfRootInScan(spec *specs.Spec) {
	if spec == nil || spec.Process == nil {
		return
	}
	if spec.Process.User.UID == 0 {
		logrus.Warn("security-scan: container runs as uid 0; kernel skips many cap_capable checks for root, so the trace will under-report. Consider setting process.user.uid to a non-zero value (e.g. 65534).")
	}
}

func allKnownCapabilityNames() []string {
	last, err := capability.LastCap()
	if err != nil {
		return nil
	}
	out := make([]string, 0, int(last)+1)
	for i := 0; i <= int(last); i++ {
		out = append(out, ociCapName(capability.Cap(i)))
	}
	return out
}

// ociCapName converts the moby/sys/capability lowercase form ("chown")
// into the uppercase CAP_-prefixed form the OCI runtime-spec mandates
// for process.capabilities ("CAP_CHOWN"). Done in one place so we never
// mix lowercase and uppercase entries inside the same cap set.
func ociCapName(c capability.Cap) string {
	return "CAP_" + strings.ToUpper(c.String())
}

// resolveRuncSelfExec returns the absolute path of the running runc
// binary so it can be wired as Hook.Path on OCI hooks. We refuse to
// install hooks pointing at a non-existent file so misconfigured runs
// fail at scan setup rather than at hook invocation time.
func resolveRuncSelfExec() (string, error) {
	bin, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("security-scan: resolve runc binary: %w", err)
	}
	bin, err = filepath.Abs(bin)
	if err != nil {
		return "", fmt.Errorf("security-scan: abs runc binary: %w", err)
	}
	if st, err := os.Stat(bin); err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
		return "", fmt.Errorf("security-scan: runc self-exec %q not usable as hook", bin)
	}
	return bin, nil
}
