package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/opencontainers/runc/libcontainer/apparmor"
	"github.com/opencontainers/runtime-spec/specs-go"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

const traceSyscallAnnotation = "io.containers.trace-syscall"

var defaultSeccompHookPaths = []string{
	"/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
	"/usr/local/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
}

var defaultCapablePaths = []string{
	"/usr/share/bcc/tools/capable",
	"/usr/sbin/capable-bpfcc",
}

const appArmorScanReadme = `AppArmor (automatic with --security-scan)
========================================

When AppArmor is enabled on the host, runc loads generated/apparmor.profile
(complain mode via profile flags) before the container runs, sets
process.apparmorProfile, and unloads the profile on poststop.

If AppArmor is disabled, the profile file is still written for reference.
See generated/apparmor-load.log after each run.
`

func buildAppArmorProfileSource(profileName string) string {
	return fmt.Sprintf(`#include <tunables/global>

profile %s flags=(complain, attach_disconnected, mediate_deleted) {
  #include <abstractions/base>
  # Auto-generated by runc --security-scan (complain mode in profile flags).
}
`, profileName)
}

func securityScanAppArmorProfileName(containerID string) string {
	const prefix = "runc_scan_"
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range containerID {
		switch {
		case unicode.IsLetter(r), unicode.IsDigit(r):
			b.WriteRune(r)
		case r == '-', r == '_':
			b.WriteByte('_')
		}
	}
	name := b.String()
	if len(name) <= len(prefix) {
		name = prefix + "x"
	}
	if len(name) > 200 {
		name = name[:200]
	}
	return name
}

func applySecurityScan(spec *specs.Spec, ctx *cli.Context, containerID string) error {
	if !ctx.Bool("security-scan") {
		return nil
	}
	bundleDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("security-scan: getwd: %w", err)
	}
	bundleDir, err = filepath.Abs(bundleDir)
	if err != nil {
		return fmt.Errorf("security-scan: abs bundle: %w", err)
	}
	genDir := filepath.Join(bundleDir, "generated")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return fmt.Errorf("security-scan: mkdir generated: %w", err)
	}

	runcBin, err := resolveRuncSelfExec()
	if err != nil {
		return err
	}

	hookPath := strings.TrimSpace(ctx.String("scan-seccomp-hook"))
	if hookPath == "" {
		for _, p := range defaultSeccompHookPaths {
			if st, err := os.Stat(p); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
				hookPath = p
				logrus.Infof("security-scan: using seccomp hook %q", hookPath)
				break
			}
		}
	}
	if hookPath == "" {
		return fmt.Errorf("security-scan: no oci-seccomp-bpf-hook found; install it or pass --scan-seccomp-hook PATH (e.g. contrib stub for tests)")
	}
	hookPath, err = filepath.Abs(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: abs hook path: %w", err)
	}
	st, err := os.Stat(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: stat seccomp hook: %w", err)
	}
	if st.IsDir() || st.Mode()&0o111 == 0 {
		return fmt.Errorf("security-scan: seccomp hook must be an executable file: %s", hookPath)
	}

	seccompOut := filepath.Join(genDir, "seccomp.json")
	annotation := "of:" + seccompOut
	if spec.Annotations == nil {
		spec.Annotations = map[string]string{}
	}
	if prev, ok := spec.Annotations[traceSyscallAnnotation]; ok && prev != annotation {
		logrus.Warnf("security-scan: overwriting annotation %q (was %q)", traceSyscallAnnotation, prev)
	}
	spec.Annotations[traceSyscallAnnotation] = annotation

	if spec.Hooks == nil {
		spec.Hooks = &specs.Hooks{}
	}
	secHook := specs.Hook{
		Path: hookPath,
		Args: []string{filepath.Base(hookPath), "-s"},
	}
	spec.Hooks.Prestart = append(spec.Hooks.Prestart, secHook)

	snapshotHook := specs.Hook{
		Path: runcBin,
		Args: []string{"runc", "scan-cap-snapshot"},
	}
	spec.Hooks.Poststart = append(spec.Hooks.Poststart, snapshotHook)

	if capBin := resolveCapableBinary(ctx); capBin != "" {
		traceScriptPath := filepath.Join(genDir, ".runc_cap_trace.sh")
		traceBody := buildCapTraceScript(bundleDir)
		if err := os.WriteFile(traceScriptPath, []byte(traceBody), 0o755); err != nil {
			return fmt.Errorf("security-scan: write poststart cap trace: %w", err)
		}
		traceHook := specs.Hook{
			Path: traceScriptPath,
			Args: []string{filepath.Base(traceScriptPath)},
			Env: []string{
				"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
				"RUNC_SCAN_CAPABLE=" + capBin,
			},
		}
		spec.Hooks.Poststart = append(spec.Hooks.Poststart, traceHook)
		logrus.Infof("security-scan: tracing used caps in background via %q (see generated/capable-bpfcc.log)", capBin)
	}

	aaProfName := securityScanAppArmorProfileName(containerID)
	aaProfPath := filepath.Join(genDir, "apparmor.profile")
	if err := os.WriteFile(aaProfPath, []byte(buildAppArmorProfileSource(aaProfName)), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor.profile: %w", err)
	}
	aaReadme := filepath.Join(genDir, "apparmor-README.txt")
	if err := os.WriteFile(aaReadme, []byte(appArmorScanReadme), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor readme: %w", err)
	}

	if apparmor.IsEnabled() {
		aaLog := filepath.Join(genDir, "apparmor-load.log")
		env := []string{
			"PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin",
			envScanAAProfilePath + "=" + aaProfPath,
			envScanAALog + "=" + aaLog,
		}
		loadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-load"},
			Env:  env,
		}
		spec.Hooks.CreateRuntime = append([]specs.Hook{loadHook}, spec.Hooks.CreateRuntime...)
		unloadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-unload"},
			Env:  env,
		}
		spec.Hooks.Poststop = append(spec.Hooks.Poststop, unloadHook)
		if spec.Process == nil {
			spec.Process = &specs.Process{}
		}
		if spec.Process.ApparmorProfile != "" && spec.Process.ApparmorProfile != aaProfName {
			logrus.Warnf("security-scan: replacing apparmorProfile %q with scan profile %q", spec.Process.ApparmorProfile, aaProfName)
		}
		spec.Process.ApparmorProfile = aaProfName
		logrus.Infof("security-scan: AppArmor profile %q (complain) will load from %q via runc self-exec", aaProfName, aaProfPath)
	} else {
		logrus.Info("security-scan: AppArmor disabled on host; wrote apparmor.profile but did not set process.apparmorProfile or hooks")
	}

	logrus.Infof("security-scan: bundle %q; artifacts under %s", bundleDir, genDir)
	return nil
}

func resolveCapableBinary(ctx *cli.Context) string {
	p := strings.TrimSpace(ctx.String("scan-capable"))
	if p != "" {
		abs, err := filepath.Abs(p)
		if err != nil {
			logrus.Warnf("security-scan: scan-capable path: %v", err)
			return ""
		}
		st, err := os.Stat(abs)
		if err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
			logrus.Warnf("security-scan: --scan-capable %q is not an executable file", abs)
			return ""
		}
		return abs
	}
	if path, err := exec.LookPath("capable-bpfcc"); err == nil {
		return path
	}
	for _, try := range defaultCapablePaths {
		if st, err := os.Stat(try); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
			return try
		}
	}
	return ""
}

func shellSingleQuote(s string) string {
	return `'` + strings.ReplaceAll(s, `'`, `'\''`) + `'`
}

// buildCapTraceScript returns a tiny /bin/sh wrapper that spawns the
// external capable-bpfcc tracer in the background. The /proc/<pid>/status
// snapshot has already been moved to the scan-cap-snapshot subcommand;
// this script is the last shell stub remaining in the bundle and will be
// replaced by scan-cap-trace-start in the next commit.
//
// In fmt.Sprintf, %% becomes a literal % in the emitted shell script, so
// %%s yields shell printf '%s' (correct for /bin/sh).
func buildCapTraceScript(bundleDir string) string {
	q := shellSingleQuote(bundleDir)
	return fmt.Sprintf(`#!/bin/sh
set -e
state=$(cat)
bundle=%s
gen="$bundle/generated"
mkdir -p "$gen"
pid=$(printf '%%s' "$state" | sed -n 's/.*"pid": *\([0-9][0-9]*\).*/\1/p' | head -n1)
if [ -z "$pid" ] || [ -z "${RUNC_SCAN_CAPABLE:-}" ] || [ ! -x "$RUNC_SCAN_CAPABLE" ]; then
  exit 0
fi
: >>"$gen/capable-bpfcc.log"
nohup "$RUNC_SCAN_CAPABLE" -p "$pid" >>"$gen/capable-bpfcc.log" 2>&1 &
`, q)
}

// resolveRuncSelfExec returns the absolute path of the running runc
// binary so it can be wired as Hook.Path on OCI hooks. We refuse to
// install hooks pointing at a non-existent file so misconfigured runs
// fail at scan setup rather than at hook invocation time.
func resolveRuncSelfExec() (string, error) {
	bin, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("security-scan: resolve runc binary: %w", err)
	}
	bin, err = filepath.Abs(bin)
	if err != nil {
		return "", fmt.Errorf("security-scan: abs runc binary: %w", err)
	}
	if st, err := os.Stat(bin); err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
		return "", fmt.Errorf("security-scan: runc self-exec %q not usable as hook", bin)
	}
	return bin, nil
}
