package main

import (
	"io"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

// Internal OCI hook subcommands used by --security-scan. These are hidden
// from --help and are invoked as Hook.Path = <runc binary> with the runc
// argv carrying the subcommand name. Each one reads the OCI hook state
// JSON from stdin (per OCI runtime spec hooks); subcommands that don't
// need it still drain stdin so the runtime never blocks on a write.

var scanAALoadHookCommand = cli.Command{
	Name:   "scan-aa-load",
	Usage:  "internal: load AppArmor profile generated by --security-scan (createRuntime hook)",
	Hidden: true,
	Action: func(ctx *cli.Context) error {
		_, _ = io.Copy(io.Discard, os.Stdin)
		logrus.Debug("scan-aa-load: not yet wired")
		return nil
	},
}

var scanAAUnloadHookCommand = cli.Command{
	Name:   "scan-aa-unload",
	Usage:  "internal: unload AppArmor profile generated by --security-scan (poststop hook)",
	Hidden: true,
	Action: func(ctx *cli.Context) error {
		_, _ = io.Copy(io.Discard, os.Stdin)
		logrus.Debug("scan-aa-unload: not yet wired")
		return nil
	},
}

var scanCapSnapshotHookCommand = cli.Command{
	Name:   "scan-cap-snapshot",
	Usage:  "internal: snapshot /proc/<pid>/status Cap* lines for --security-scan (poststart hook)",
	Hidden: true,
	Action: func(ctx *cli.Context) error {
		_, _ = io.Copy(io.Discard, os.Stdin)
		logrus.Debug("scan-cap-snapshot: not yet wired")
		return nil
	},
}

var scanCapTraceStartHookCommand = cli.Command{
	Name:   "scan-cap-trace-start",
	Usage:  "internal: spawn external capable-bpfcc trace for --security-scan (poststart hook)",
	Hidden: true,
	Action: func(ctx *cli.Context) error {
		_, _ = io.Copy(io.Discard, os.Stdin)
		logrus.Debug("scan-cap-trace-start: not yet wired")
		return nil
	},
}

var scanCapTraceStopHookCommand = cli.Command{
	Name:   "scan-cap-trace-stop",
	Usage:  "internal: stop the capable-bpfcc trace started by --security-scan (poststop hook)",
	Hidden: true,
	Action: func(ctx *cli.Context) error {
		_, _ = io.Copy(io.Discard, os.Stdin)
		logrus.Debug("scan-cap-trace-stop: not yet wired")
		return nil
	},
}
