package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/moby/sys/capability"
	"github.com/opencontainers/runc/libcontainer/apparmor"
	"github.com/opencontainers/runtime-spec/specs-go"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

const traceSyscallAnnotation = "io.containers.trace-syscall"

var defaultSeccompHookPaths = []string{
	"/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
	"/usr/local/libexec/oci/hooks.d/oci-seccomp-bpf-hook",
}

var defaultCapablePaths = []string{
	"/usr/share/bcc/tools/capable",
	"/usr/sbin/capable-bpfcc",
}

const appArmorScanReadme = `AppArmor (automatic with --security-scan)
========================================

During the scan run runc writes generated/apparmor.profile (a stub in
complain mode with abstractions/base, nameservice, ssl_certs included),
loads it via apparmor_parser -r, sets process.apparmorProfile, and
records every apparmor=DENIED audit line for the profile in the kernel
ring. On poststop the runtime pulls those denials out of journalctl
(or dmesg as a fallback), turns them into file and capability rules,
and appends them between sentinel markers inside the profile body.

After the container exits, finalizeSecurityScan:
  * writes the profile name into process.apparmorProfile in config.json,
  * flips the on-disk profile out of complain mode into enforce when
    audit-collected rules are present (otherwise complain stays).

Subsequent non-scan runc invocations on the same bundle pick the
profile up automatically: ensureGeneratedProfiles loads it via
apparmor_parser -r before starting the container.

If AppArmor is disabled on the host the profile file is still written
for reference; load/unload and audit collection are skipped. See
generated/apparmor-load.log after each run for diagnostics.
`

// buildAppArmorProfileSource emits the stub profile we load before
// the container starts. It is intentionally minimal: only abstractions
// that every reasonable Linux workload needs (base, name service for
// DNS, ssl certs for TLS) are pulled in, so the kernel audit log
// surfaces denials for everything else. The poststop audit collector
// then turns those denials into explicit rules and finalize flips the
// profile out of complain mode into enforce.
func buildAppArmorProfileSource(profileName string) string {
	return fmt.Sprintf(`#include <tunables/global>

profile %s flags=(complain, attach_disconnected, mediate_deleted) {
  #include <abstractions/base>
  #include <abstractions/nameservice>
  #include <abstractions/ssl_certs>
  # Auto-generated by runc --security-scan (complain mode in profile flags).
  # The poststop audit collector appends file/capability rules between
  # the BEGIN/END markers; finalize flips the profile to enforce once
  # the markers are present.
}
`, profileName)
}

func securityScanAppArmorProfileName(containerID string) string {
	const prefix = "runc_scan_"
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range containerID {
		switch {
		case unicode.IsLetter(r), unicode.IsDigit(r):
			b.WriteRune(r)
		case r == '-', r == '_':
			b.WriteByte('_')
		}
	}
	name := b.String()
	if len(name) <= len(prefix) {
		name = prefix + "x"
	}
	if len(name) > 200 {
		name = name[:200]
	}
	return name
}

func applySecurityScan(spec *specs.Spec, ctx *cli.Context, containerID string) error {
	if !ctx.Bool("security-scan") {
		return nil
	}
	bundleDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("security-scan: getwd: %w", err)
	}
	bundleDir, err = filepath.Abs(bundleDir)
	if err != nil {
		return fmt.Errorf("security-scan: abs bundle: %w", err)
	}
	genDir := filepath.Join(bundleDir, "generated")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return fmt.Errorf("security-scan: mkdir generated: %w", err)
	}

	runcBin, err := resolveRuncSelfExec()
	if err != nil {
		return err
	}

	relaxSpecForScan(spec)
	grantAllCapsForScan(spec)
	warnIfRootInScan(spec)

	hookPath := strings.TrimSpace(ctx.String("scan-seccomp-hook"))
	if hookPath == "" {
		for _, p := range defaultSeccompHookPaths {
			if st, err := os.Stat(p); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
				hookPath = p
				logrus.Infof("security-scan: using seccomp hook %q", hookPath)
				break
			}
		}
	}
	if hookPath == "" {
		return fmt.Errorf("security-scan: no oci-seccomp-bpf-hook found; install it or pass --scan-seccomp-hook PATH (e.g. contrib stub for tests)")
	}
	hookPath, err = filepath.Abs(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: abs hook path: %w", err)
	}
	st, err := os.Stat(hookPath)
	if err != nil {
		return fmt.Errorf("security-scan: stat seccomp hook: %w", err)
	}
	if st.IsDir() || st.Mode()&0o111 == 0 {
		return fmt.Errorf("security-scan: seccomp hook must be an executable file: %s", hookPath)
	}

	seccompOut := filepath.Join(genDir, "seccomp.json")
	annotation := "of:" + seccompOut
	if spec.Annotations == nil {
		spec.Annotations = map[string]string{}
	}
	if prev, ok := spec.Annotations[traceSyscallAnnotation]; ok && prev != annotation {
		logrus.Warnf("security-scan: overwriting annotation %q (was %q)", traceSyscallAnnotation, prev)
	}
	spec.Annotations[traceSyscallAnnotation] = annotation

	if spec.Hooks == nil {
		spec.Hooks = &specs.Hooks{}
	}
	secHook := specs.Hook{
		Path: hookPath,
		Args: []string{filepath.Base(hookPath), "-s"},
	}
	spec.Hooks.Prestart = append(spec.Hooks.Prestart, secHook)

	snapshotHook := specs.Hook{
		Path: runcBin,
		Args: []string{"runc", "scan-cap-snapshot"},
	}
	spec.Hooks.Poststart = append(spec.Hooks.Poststart, snapshotHook)

	capBin, bpftoolBin, err := requireCapTraceTools(ctx)
	if err != nil {
		return err
	}
	traceEnv := []string{
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		envScanCapableBin + "=" + capBin,
		envScanBpftool + "=" + bpftoolBin,
		envScanContainerID + "=" + containerID,
	}
	// Propagate the pin-root override the same way Path/binary paths
	// flow through Hook.Env so integration tests can route bpftool to
	// a tmp dir; production callers leave the var unset.
	if v := os.Getenv("RUNC_SCAN_PIN_ROOT"); v != "" {
		traceEnv = append(traceEnv, "RUNC_SCAN_PIN_ROOT="+v)
	}
	if v := os.Getenv("RUNC_STUB_BPFTOOL_LOG"); v != "" {
		traceEnv = append(traceEnv, "RUNC_STUB_BPFTOOL_LOG="+v)
	}
	spec.Hooks.Poststart = append(spec.Hooks.Poststart, specs.Hook{
		Path: runcBin,
		Args: []string{"runc", "scan-cap-trace-start"},
		Env:  traceEnv,
	})
	// Stop hook is prepended so it runs before AA-unload and any
	// other poststop hook a user (or we) might add later. The hook
	// itself is also our barrier: by the time finalizeSecurityScan
	// runs, the tracer has exited and capable-bpfcc.log is closed.
	// Same env so it can locate and unpin the per-container BPF map.
	spec.Hooks.Poststop = append([]specs.Hook{{
		Path: runcBin,
		Args: []string{"runc", "scan-cap-trace-stop"},
		Env:  traceEnv,
	}}, spec.Hooks.Poststop...)
	logrus.Infof("security-scan: cgroup-wide cap trace via %q with cgroupmap (see generated/%s)", capBin, scanCapTraceLogFile)

	aaProfName := securityScanAppArmorProfileName(containerID)
	aaProfPath := filepath.Join(genDir, "apparmor.profile")
	// Unload any profile a previous (possibly crashed or differently-id'd)
	// scan run left behind on this bundle so the kernel does not keep the
	// old policy loaded under its old name. Soft error: missing parser, a
	// fresh bundle, or a disabled LSM are all expected on first run.
	cleanupStaleAppArmorProfile(aaProfPath)
	if err := os.WriteFile(aaProfPath, []byte(buildAppArmorProfileSource(aaProfName)), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor.profile: %w", err)
	}
	aaReadme := filepath.Join(genDir, "apparmor-README.txt")
	if err := os.WriteFile(aaReadme, []byte(appArmorScanReadme), 0o644); err != nil {
		return fmt.Errorf("security-scan: write apparmor readme: %w", err)
	}

	if apparmor.IsEnabled() {
		aaLog := filepath.Join(genDir, "apparmor-load.log")
		env := []string{
			"PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin",
			envScanAAProfilePath + "=" + aaProfPath,
			envScanAALog + "=" + aaLog,
		}
		loadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-load"},
			Env:  env,
		}
		spec.Hooks.CreateRuntime = append([]specs.Hook{loadHook}, spec.Hooks.CreateRuntime...)
		unloadHook := specs.Hook{
			Path: runcBin,
			Args: []string{"runc", "scan-aa-unload"},
			Env:  env,
		}
		spec.Hooks.Poststop = append(spec.Hooks.Poststop, unloadHook)
		if spec.Process == nil {
			spec.Process = &specs.Process{}
		}
		if spec.Process.ApparmorProfile != "" && spec.Process.ApparmorProfile != aaProfName {
			logrus.Warnf("security-scan: replacing apparmorProfile %q with scan profile %q", spec.Process.ApparmorProfile, aaProfName)
		}
		spec.Process.ApparmorProfile = aaProfName
		logrus.Infof("security-scan: AppArmor profile %q (complain) will load from %q via runc self-exec", aaProfName, aaProfPath)
	} else {
		logrus.Info("security-scan: AppArmor disabled on host; wrote apparmor.profile but did not set process.apparmorProfile or hooks")
	}

	logrus.Infof("security-scan: bundle %q; artifacts under %s", bundleDir, genDir)
	return nil
}

// requireCapTraceTools resolves the binaries and host preconditions
// the eBPF cgroup-wide cap trace needs and returns a clear error if
// any of them is missing. The trace is mandatory in scan mode (see
// review-scanner.mdc req[4]); without --cgroupmap support we cannot
// guarantee that child processes are observed, so we refuse to run
// rather than silently degrading. scripts/setup-env.sh from this repo
// installs everything required.
func requireCapTraceTools(ctx *cli.Context) (capBin, bpftoolBin string, err error) {
	capBin = resolveCapableBinary(ctx)
	if capBin == "" {
		return "", "", fmt.Errorf("security-scan: capable-bpfcc not found; install bpfcc-tools or pass --scan-capable PATH (see scripts/setup-env.sh)")
	}
	if !capableSupportsCgroupmap(capBin) {
		return "", "", fmt.Errorf("security-scan: %q has no --cgroupmap option; install a newer bpfcc-tools (see scripts/setup-env.sh)", capBin)
	}
	bpftoolBin = resolveBpftoolBinary(ctx)
	if bpftoolBin == "" {
		return "", "", fmt.Errorf("security-scan: bpftool not found; install linux-tools-common or pass --scan-bpftool PATH (see scripts/setup-env.sh)")
	}
	if !cgroupV2InUse() {
		return "", "", fmt.Errorf("security-scan: requires cgroup v2 unified hierarchy; this host is on v1 or hybrid")
	}
	// Skip the bpffs precondition when tests have routed pinning to a
	// regular dir. Production code never sets RUNC_SCAN_PIN_ROOT.
	if os.Getenv("RUNC_SCAN_PIN_ROOT") == "" && !bpffsMounted() {
		return "", "", fmt.Errorf("security-scan: /sys/fs/bpf is not bpffs; mount with `mount -t bpf bpffs /sys/fs/bpf` or run scripts/setup-env.sh")
	}
	return capBin, bpftoolBin, nil
}

func resolveCapableBinary(ctx *cli.Context) string {
	p := strings.TrimSpace(ctx.String("scan-capable"))
	if p != "" {
		return validatedExecutable(p, "--scan-capable")
	}
	if path, err := exec.LookPath("capable-bpfcc"); err == nil {
		return path
	}
	for _, try := range defaultCapablePaths {
		if st, err := os.Stat(try); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
			return try
		}
	}
	return ""
}

func resolveBpftoolBinary(ctx *cli.Context) string {
	p := strings.TrimSpace(ctx.String("scan-bpftool"))
	if p != "" {
		return validatedExecutable(p, "--scan-bpftool")
	}
	if path, err := exec.LookPath("bpftool"); err == nil {
		return path
	}
	for _, try := range []string{"/usr/sbin/bpftool", "/usr/local/sbin/bpftool"} {
		if st, err := os.Stat(try); err == nil && !st.IsDir() && st.Mode()&0o111 != 0 {
			return try
		}
	}
	return ""
}

func validatedExecutable(p, flag string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		logrus.Warnf("security-scan: %s path: %v", flag, err)
		return ""
	}
	st, err := os.Stat(abs)
	if err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
		logrus.Warnf("security-scan: %s %q is not an executable file", flag, abs)
		return ""
	}
	return abs
}

// relaxSpecForScan turns off the host-supplied security policies that
// would otherwise muffle the trace. We need every syscall and every
// capability check to actually reach the kernel hooks our tracers ride
// on, so seccomp/SELinux/NoNewPrivileges are stripped from the spec for
// the duration of the scan run. The on-disk config.json is left alone
// at this stage; finalizeSecurityScan reconstructs caps and seccomp on
// disk from the trace artefacts after the container exits, and copies
// the untouched pre-scan config to generated/spec.original.json so the
// rollback target is preserved. SELinux is out of scope: the label is
// cleared in memory so it does not mask the trace, but no SELinux
// policy is generated and the on-disk label, if any, stays as it was.
//
// AppArmor is handled separately further down in applySecurityScan: the
// generated complain-mode profile is what gets wired in via
// process.apparmorProfile during the scan run; finalize then picks the
// profile name out of the on-disk file and writes it back into the spec.
func relaxSpecForScan(spec *specs.Spec) {
	if spec == nil {
		return
	}
	var cleared []string
	if spec.Linux != nil && spec.Linux.Seccomp != nil {
		spec.Linux.Seccomp = nil
		cleared = append(cleared, "linux.seccomp")
	}
	if spec.Process != nil {
		if spec.Process.SelinuxLabel != "" {
			spec.Process.SelinuxLabel = ""
			cleared = append(cleared, "process.selinuxLabel")
		}
		if spec.Process.NoNewPrivileges {
			spec.Process.NoNewPrivileges = false
			cleared = append(cleared, "process.noNewPrivileges")
		}
	}
	if len(cleared) > 0 {
		logrus.Infof("security-scan: relaxed in-memory spec fields: %s", strings.Join(cleared, ", "))
	}
}

// grantAllCapsForScan replaces process.capabilities with the full set
// of capabilities the running kernel knows about. Combined with the
// non-root uid recommendation, this gives the application enough
// privilege to perform every operation it would attempt in production
// while still routing every privileged check through cap_capable so
// the BCC tracer can record it. The set is written into all five OCI
// capability buckets (bounding/effective/permitted/inheritable/ambient)
// so caps survive across exec(2).
//
// finalizeSecurityScan then narrows the on-disk config.json down to
// the caps actually observed during the run, so this in-memory grant
// is never persisted.
func grantAllCapsForScan(spec *specs.Spec) {
	if spec == nil {
		return
	}
	caps := allKnownCapabilityNames()
	if len(caps) == 0 {
		logrus.Warn("security-scan: kernel reported no capabilities; cap-trace coverage will be limited")
		return
	}
	if spec.Process == nil {
		spec.Process = &specs.Process{}
	}
	if spec.Process.Capabilities == nil {
		spec.Process.Capabilities = &specs.LinuxCapabilities{}
	}
	spec.Process.Capabilities.Bounding = caps
	spec.Process.Capabilities.Effective = caps
	spec.Process.Capabilities.Permitted = caps
	spec.Process.Capabilities.Inheritable = caps
	spec.Process.Capabilities.Ambient = caps
	logrus.Infof("security-scan: granted %d capabilities for scan run (will be narrowed by finalize)", len(caps))
}

// warnIfRootInScan logs a warning when the bundle asks for uid 0.
// We do not rewrite the spec - some workloads genuinely need root and
// forcing a non-root uid would break them - but cap_capable is only
// called for non-root tasks, so the cap-trace coverage degrades sharply
// when the init process runs as root. Documented in SCANNER_PROGRESS.
func warnIfRootInScan(spec *specs.Spec) {
	if spec == nil || spec.Process == nil {
		return
	}
	if spec.Process.User.UID == 0 {
		logrus.Warn("security-scan: container runs as uid 0; kernel skips many cap_capable checks for root, so the trace will under-report. Consider setting process.user.uid to a non-zero value (e.g. 65534).")
	}
}

func allKnownCapabilityNames() []string {
	last, err := capability.LastCap()
	if err != nil {
		return nil
	}
	out := make([]string, 0, int(last)+1)
	for i := 0; i <= int(last); i++ {
		out = append(out, ociCapName(capability.Cap(i)))
	}
	return out
}

// ociCapName converts the moby/sys/capability lowercase form ("chown")
// into the uppercase CAP_-prefixed form the OCI runtime-spec mandates
// for process.capabilities ("CAP_CHOWN"). Done in one place so we never
// mix lowercase and uppercase entries inside the same cap set.
func ociCapName(c capability.Cap) string {
	return "CAP_" + strings.ToUpper(c.String())
}

// cleanupStaleAppArmorProfile best-effort unloads an AppArmor profile
// left behind on disk by a previous scan run. It is safe to call
// before writing a fresh profile: a missing file, a parser-less host,
// or a disabled LSM are all expected and silenced. The intent is to
// keep the kernel's profile table from growing under repeated scans
// of bundles whose container id changed between runs, and to recover
// cleanly from a crash that left an older profile installed.
func cleanupStaleAppArmorProfile(path string) {
	if path == "" {
		return
	}
	if _, err := os.Stat(path); err != nil {
		return
	}
	if !apparmor.IsEnabled() {
		return
	}
	parser, err := exec.LookPath("apparmor_parser")
	if err != nil {
		return
	}
	cmd := exec.Command(parser, "-R", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		logrus.Debugf("security-scan: stale apparmor_parser -R %s: %v: %s",
			path, err, strings.TrimSpace(string(out)))
	}
}

// resolveRuncSelfExec returns the absolute path of the running runc
// binary so it can be wired as Hook.Path on OCI hooks. We refuse to
// install hooks pointing at a non-existent file so misconfigured runs
// fail at scan setup rather than at hook invocation time.
func resolveRuncSelfExec() (string, error) {
	bin, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("security-scan: resolve runc binary: %w", err)
	}
	bin, err = filepath.Abs(bin)
	if err != nil {
		return "", fmt.Errorf("security-scan: abs runc binary: %w", err)
	}
	if st, err := os.Stat(bin); err != nil || st.IsDir() || st.Mode()&0o111 == 0 {
		return "", fmt.Errorf("security-scan: runc self-exec %q not usable as hook", bin)
	}
	return bin, nil
}
